language: python
git:
  depth: 3
  lfs_skip_smudge: true
  submodules: false
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - nightly
  - pypy
  # - pypy3
matrix:
  include:
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=2.7
      python: 2.7
      before_install: pyenv install $TRAVIS_PYTHON_VERSION
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.5
      python: 3.5
      before_install: pyenv install 3.5.0
  allow_failures:
    - os: osx
    - python: 2.6
    - python: 3.7-dev
    - python: nightly
    - python: pypy
    # - python: pypy3
  fast_finish: true
cache: pip
install:
  - pip install -U setuptools
  - pip install -U tox
  # - pip install scrutinizer-ocular
  - pip install tox-travis
script: tox --skip-missing-interpreters
after_script:
  - tox -e check
  - tox -e dups
  - tox -e pylint -- -E
# after_success: ocular
before_deploy:
  - test $TRAVIS_TEST_RESULT -eq 0
  - test $TRAVIS_OS_NAME = linux
deploy:
  - provider: pypi
    user:
      secure: "Q2ysZhMhFjhAtsZ+Ny+19VIx0M9Axax/uB7RmKKZOF0vguUroyadQjBsC8e9YkR4I+J4VDZQ5YacYpPsH/YfFdBveJ8I7Czgq1q9o92+ZB9m1KapDWAS2y6sOndvWdLxFkazedf/4QqsY+TkyDgZ2fmpRfmw0qi10z8+VCuqDErJwWUHIvOmG9CWP8Ds50iBvFjQbW+6XGgTWigDr2sjIL4thtYdar7iFllQ6TS9JASXMMSGInHma9Za2uKipkQDpiaVlueJTGbmjhmx+Mnbk2Nu5zgBT5k6puwUpRX5nL8icU9vim6XMfjXqI0Bg3aXYZ6wkevUJaGbeD97YWOnOe2KAklKF8Hvt5+TDpihND31RE1uLu0mMxSegIbEmTapG9QT91rNKHWkFjadz2NClO7vwTf7S0N7kNbwhEPshCvrESH1aiol3bSRFXVOoD3lI6hZ6gVQHOVVFPobeJFAtvTn4GarNFmTYzI0jxTaPO6m3ij1wWabrShPAzzPjkJ+U/3qC+kHI+dZAENz4gDP2jr4teFIPq/D75zVK5X6SdCEgq7Ti+5FHyxAJU9JDHXZRATGVdXI1s4i2Nb6Egjatj8aw8UxJGyoH2T48YHSINlGchMnOzwE3RZ6pcsUrwrz3nD+6tuvV/WCpZ4192G9a/dptKOI3m4kusGa1Ejfa+I="
    password:
      secure: "yYhtBCC6EmVlCAG3nU2uOmtGz1Vr+gU807nAnv5HjIOFEZe1U2LQ3iWEJjupZWxli2k/Xae3CSi/Q7jAuqLDcFhJTZEO5Z/dCXiMDS/nO98FcKCvWm5qTVQsNa9HpZ+DxhJoguorI2XNjHCNNAm2xXpYGt8UWDs097k6vMEEmEK7Dk9gtwo6alVPgtsG5NX4pb0+w1vFLcfLAkSKhEshe4lcI0sTNwNqTwORmCMZ4BHotaUWwf1bJi3UYkXtfIlT35/dNZYGDVWruljIFWI+dMkEJ5q8r+W/khiB03nSa3xQYx35V+KmEIpX7gX7zxk15XtOfwVYqymAM+YhCHBG9GRJIPwelbGPyDb0C74xDv5VKXbtLKw/baynO20xGnQkiV+Tv7M6lizleDWBYXzruIDFk6nFir4U4CydLEoAcfUgR0kgvSgaPT9TwulgrH46jTvIXCdCwe6PMRHI7uWT4o1q+MZ10lkkiPPJNznx2IH1S9BMHPQR5gw8Q3bGVcsOHp2vvviK4pM7nCC+qYxDXECKIl8bKUmp/Y4r+n4DiYhJtxdMgBqNcbEVsh746bO1rLLdz5RPxw4F0z0IDwO/PAfH6M4cjtC8ta4tkjQWq9yNAmGsGicDJN8FEUC3+jyNiKDDDqvRlz6sKxIlZ7LGc1ZMFeHSf0/bBHMh/96opRI="
    distributions: sdist bdist_wheel
    skip_cleanup: true
    skip_upload_docs: true
    on:
      python: 3.5
      tags: true
  - provider: releases
    api-key:
      secure: "BI72sJw+rfJv5c0oWio5b6E0tPie2XnqgjSQJvLP6LAbePdg365sW1DU6Ly3UZz9rK0N/sjPSYX/z8K++IjmnZazIYPShj+t5z3AFhvjmWuIYK9N16u0nGh4IYwGkvRYXLPwjVGUe2P97QuatZfoG7iDYkn9xfvwPQVP63x0N0HNjj3o1p1r1SMhcW4MyrLUygAl/dlVNhNuTKSue2GTitfBimvgxUuQVjiTpVmGNXgKjl9wH0coxW+XaoG+QLpj7SpegLTEAddJcPm3qoTzA8fJui7S2t1/aOJEMba7+ZIIMd7xW6XHD75ab62ixDAd9mg2nvnqcuqNq9BueImxg9EKXUK+86KDwqrjv5ry9QVOjhGMxMnFVTF0iSDMi/ZQ9K0YWaZWKReSLDcjMkkkQPp5ul8TLTz1+fYElmfqshMZzuuyTCOjwJKKgtGIjABusLVNFqAd7SxDXG1WfL/j/ssAqn0sgrW5NPFJxUXPpQaYgVB24aZOAdZ/qiTH1F41ZmyRUETrBRfUXEI3PDf0krBotG8ALVgdlmleYSLZkUbAKcE/uADuwvwA1T0Vv7hfVaAqc8n768Rar7+HWq0C8Pz5nEDochzLRnLOBDIivZUDBQTmkLGA/sE4jBRXQwAWAsMADlpvphHOajzrw1ZYxbkgLaE578cye8M0HoS0TD8="
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      python: 3.5
      tags: true
      name: "${$TRAVIS_REPO_SLUG#*/} ${$TRAVIS_TAG#v}"
      body: "## Changelog"
